name: cogtext

channels:
  - conda-forge
  - defaults

dependencies:

  # dev tools
  - python
  - pip
  - dvc
  - ipykernel
  - ipywidgets
  - flake8
  - python-dotenv
  - watermark
  - tqdm

  # data
  - xmltodict
  - pandas
  - polars
  - pyarrow

  # visualization
  - matplotlib
  - seaborn
  - wordcloud

  # deep learning and NLP
  - pytorch
  - sentence-transformers
  - safetensors

  # ML
  - scikit-learn
  - hdbscan
  - umap-learn

  # ontologies
  - owlready2
  - rdflib

  # the rest
  # - python-igraph
  # - pydot  # keras uses pydot to plot models
  # - cairocffi  # igraph requires cairo binding
  # - cairo

  # - pip:
    # - dask[dataframe]
    # - openai
    # - gensim
    # - nltk
    # - spacy
    # - pyldavis  # visualize topic models
    # - spacy-streamlit
    # - python-Levenshtein  # used by gensim
    # - bokeh
    # - pyvis
    # - tensorflow
    # - tensorflow-probability
    # - umap-learn[parametric_umap]  # parametric UMAP
    # - top2vec   # deep topic modeling
    # - pigeon-jupyter  # annotation
    # - pigeonXT-jupyter  # improved annotation
    # - sympy  # symbolic math and matrix ranks
    # - tensorflow_hub  # to access pretrained models of tf-hub
