---
title: "Reviewing Miyake and Friedman (2000)"
author: "Pedro"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    numbered_sections: true
    theme: cerulean
    code_folding: hide
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../outputs/R_notebook/") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, 
                      fig.path = "../outputs/R_notebook/")
```



```{r load_packages}
library(tidyverse)
library(plotly)
library(lavaan)
library(broom)
library(GGally)
```



```{r}

# Pearson Correlation Coefficients for the 15 Measures (N   137 Unless Noted)
cor_values <- c(1, 
                .32,   1,
                .23,   .32,   1,
                .23,   .08,   .12,   1,
                .22,   .19,   .00,   .15,   1,
                .24,   .11,   .21,   .34,   .27,   1,
                .15,   .17,   .11,   .12,   .26,  .22,    1,
                .11,   .13,   .06,   .10,   .09,  .04,    .19,  1, 
                .07,   .09,  -0.05,   .11,   .16,  .18,    .20,   .18,  1,
                .26,   .13,   .18,   .09,   .19,  .14,    .15, -0.01,   .10,   1,
                .08,   .10,  -0.09,   .13,   .18,  .14,    .21,   .08,   .17, -0.02,   1,
                .20,   .13,   .01,   .03,   .11,  .19,    .24,   .12,   .11,   .13,   .10,  1,  
                .20,  -0.07,   .07,   .29,   .06,  .19,    .02,   .18,   .01, -0.08,   .12,   .02,  1,
                .09,   .08,  -0.04,   .41,   .28,  .34,    .16,   .13,   .20,   .16,   .04,   .17,   .13,  1,
                -0.03, -0.02,  .05, -0.09, -0.03,  .12,  -0.08, -0.16,   .06,   .06, -0.18, -0.05, -0.09, -0.14, 1)


var_names <- c(
  "Plus–minus",
  "Number–letter",
  "Local–global",
  "Keep track",
  "Tone monitoring",
  "Letter memory",
  "Antisaccade",
  "Stop-signal",
  "Stroop",
  "WCST perseveration",
  "TOH",
  "RNG Component 1",
  "RNG Component 2",
  "Operation span",
  "Dual task")

# probably also need shorter names
n_data = 137


# put data into useful format:
cor_mat <- lav_matrix_lower2full(cor_values)

# name the rows and columns
rownames(cor_mat) <- var_names
colnames(cor_mat) <- var_names
# cor_mat


## mean, sd etc for some tasks:
var_1 <- c("Plus–minus",
           "Number–letter", 
           "Local–global", 
           "Keep track",
           "Tone monitoring",
           "Letter memory",
           "Antisaccade", 
           "Stop-signal", 
           "Stroop")

m_values <- c(15.5, 546, 210, .63, .70, .99, 1.16, .78, 166)
sd_values <- c(10.8, 250,160, .14, .26, .13, .16, .29, 60)

# other measures in the paper, not included here: skewness, kurtosis, reliability


var_2 <- c(
  "WCST perseveration",
  "TOH",
  "RNG Component 1",
  "RNG Component 2",
  "Operation span",
  "Dual task")

m_values_2 <- c(32, 46, 0, 0, 43, .89)
sd_values_2 <- c(12, 12, 1, 1, 6, .13)

myiake_m <- data.frame(variables = c(var_1, var_2), 
                       mean = c(m_values, m_values_2), 
                       sd = c(sd_values, sd_values_2))


```


```{r}
# define functions

fit_random <- function(){

  # define random model:
  vars_rnd <- sample(9, 9)
  comp <- list()
  comp[[1]] <- paste0('X', vars_rnd[1:3], collapse = " + ")
  comp[[2]] <- paste0('X', vars_rnd[4:6], collapse = " + ")
  comp[[3]] <- paste0('X', vars_rnd[7:9], collapse = " + ")
  
  model_short <- paste0(comp[[1]], '; ', comp[[2]], '; ', comp[[3]])
  myiake_model_rnd <- paste0(
    'shifting  =~ ', comp[[1]],'\n',       
    'updating =~ ', comp[[2]],'\n',       
    'inhibition   =~ ', comp[[3]]       
  )
  
  # fit the model
  fit_rnd <- cfa(myiake_model_rnd, sample.cov = cor_mat_cfa,  sample.nobs = 137)
  
  # display summary output
  # tidy_cfa_output(fit_rnd, model_short)
  tidy_cfa_output_err(fit_rnd, model_short)
}


tidy_cfa_output_err <- function(cfa_fit, model_name){
  tryCatch(results <- tidy_cfa_output(cfa_fit, model_name),
           # fitMeasures(cfa_fit) ,
           error = function(e) {
             results <- tibble(
               npar = NA,
               rmsea = NA,
               chisq = NA,
               aic = NA,
               bic = NA,
               model = model_name
             )
             
           }
  )
  results
}

tidy_cfa_output <- function(cfa_fit, model_name){
  
  res <- fitMeasures(cfa_fit) 
  
  results <- tibble(
    npar = res["npar"],
    rmsea = res["rmsea"],
    chisq = res["chisq"],
    aic = res["aic"],
    bic = res["bic"],
    model = model_name
  )
  results
}




```


```{r} 
## confirmatory factor analysis in lavaan:
# reproducing fig2 from miyake 2000
cor_mat_cfa <- cor_mat[1:9, 1:9]
# cor_mat_cfa
cor_mat_cfa_names <- row.names(cor_mat_cfa)
row.names(cor_mat_cfa) <- colnames(cor_mat_cfa) <- paste0("X", 1:9)
# cor_mat_cfa


# specify the model
myiake_model <- '
shifting   =~ X1 + X2 + X3      
updating   =~ X4 + X5 + X6
inhibition =~ X7 + X8 + X9'


# fit the model
myiake_fit <- cfa(myiake_model, sample.cov = cor_mat_cfa,  sample.nobs = 137)
myiake_fit_summary <- tidy_cfa_output(myiake_fit, "myiake")

# display summary output
sm <- summary(myiake_fit, fit.measures=TRUE)

fm <- as.data.frame(fitMeasures(myiake_fit))
fm

cor_mat_cfa[cor_mat_cfa == 0] <- 0.001

# split_n <- c(3, 3, 3)





## ----- ##
cfa_boot <- data.frame()
for (ii in 1:1000){
  tmp <- fit_random()  
  tmp$boot <- ii
  cfa_boot <- rbind(cfa_boot, tmp)
}



ggplot(cfa_boot, aes(bic)) + geom_density() +
  geom_histogram() +
  geom_vline(xintercept = myiake_fit_summary$bic)


cfa_boot[which.min(cfa_boot$bic),]
cfa_boot$names


# bic


```

```{r} 
# ---- what does Miyake's data look like? ---- #

N <- 137
latent_vars_name <- c("shift", "update", "inhibit")
latent_vars_cov <- rbind(c(1, .56, .42), 
                         c(.56, 1, .63), 
                         c(.42, .63, 1))
row.names(latent_vars_cov) <- latent_vars_name
colnames(latent_vars_cov) <- latent_vars_name
# latent_vars_cov



n_tasks <- 9
# Coef_per task 
L <- cbind(c(.59, 0, 0), 
      c(.57, 0, 0), 
      c(.46, 0, 0), 
      c(0, .46, 0),
      c(0, .45, 0),
      c(0, .63, 0),
      c(0, 0, .57),
      c(0, 0, .33),
      c(0, 0, .40))

L_vector <- c(.59, .57, .46, .46, .45, .63, .57, .33, .40)

# generate data
LV <- mvtnorm::rmvnorm(n = N, mean = c(0, 0, 0), sigma = latent_vars_cov)

Task <- LV %*% L # this becomes the new mean

error_var <- c(.81, .82, .89, .89, .89, .78, .82, .94, .92)
# error_var <- c(0, 1, 0, 1, 0, 0, 1, 1, 0)
# Task_cov <- (1 - L_vector^2) + error_var
Task_cov <- error_var


# matrix(rep(Task_cov, N), nrow = N, byrow = T)
ndata <- N*n_tasks

mm <- matrix(rnorm(ndata, 0, Task_cov), nrow = N, byrow = T)
  # sd(mm[,2])
  # apply(mm, 2, sd)
Y <- Task + mm

# 
# cor_mat_boot
cor_mat_boot <- round(cor(Y), 2)

boot_r <- cor_mat_boot[lower.tri(cor_mat_boot)]
myiake_r <- cor_mat_cfa[lower.tri(cor_mat_cfa)]

plot(myiake_r, boot_r)
# cor(Y)

# plot(Y[,1], Y[,2])
# plot(Y[,1], Y[,3])
# plot(Y[,1], Y[,4])
# plot(Task[,4], Task[,5])
# cor(Task[,4], Task[,5])


# # library(car)
# # scatterplot(x = Y)
# pairs(Y, lower.panel = T)
# # error_var_m <- matrix(rep(x = error_var, times = N), nrow = N, byrow = T)
# # E <- matrix(rnorm(n = N*n_tasks, mean = 0, sd = 1), ncol = n_tasks)
# # E
# # Task + error_var_m * E
# # 
# # 
# # E *  c(0, 1, 10, 0, 1, 10, 0, 10, 100)
# # error_var
# 
# 
# panel.cor <- function(x, y, digits = 2, cex.cor, ...)
# {
#   usr <- par("usr"); on.exit(par(usr))
#   par(usr = c(0, 1, 0, 1))
#   # correlation coefficient
#   r <- cor(x, y)
#   txt <- format(c(r, 0.123456789), digits = digits)[1]
#   txt <- paste("r= ", txt, sep = "")
#   text(0.5, 0.6, txt)
#   
#   # p-value calculation
#   p <- cor.test(x, y)$p.value
#   txt2 <- format(c(p, 0.123456789), digits = digits)[1]
#   txt2 <- paste("p= ", txt2, sep = "")
#   if(p<0.01) txt2 <- paste("p= ", "<0.01", sep = "")
#   text(0.5, 0.4, txt2)
# }
# 
# pairs(Y, upper.panel = panel.cor)

```

```{r} 

D <- data.frame(Y)
names(D) <- paste0("V", 1:9)

ggpairs(D)

```

